language: node_js
node_js:
  - "stable"

before_script:
  - "rm -rf package-lock.json node_modules"
  - "yarn gatsby"

script:
  - "yarn && yarn run deploy"

deploy:
  provider: script
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
