language: node_js
os: windows
before_script:
  - npm install -g gatsby
node_js:
  - "10"
deploy:
  provider: script
  script: rm -rf yarn.lock node_modules .cache && ls && npm install && npm run deploy
  skip_cleanup: true
  on:
    branch: source