language: node_js
node_js:
  - "stable"
script:
  - "ls"
  - "rm -rf node_modules yarn.lock"
  - "npm install"
after_success:
  - "rm -rf package-lock.json"
  - "ls"
  - "gatsby -v"
  - "gatsby build"
  - "gh-pages -d public -b master"

deploy:
  provider: script
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
