language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: source
before_script:
  - "npm install -g gatsby"
  - "npm install"
script:
  - "npm run deploy"