language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "10"
deploy:
  provider: script
  script: ls rm -rf yarn.lock && ls && yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: source