language: node_js
node_js:
  - "stable"
deploy:
  provider: script
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: source
before_script:
  - "rm -rf package-lock.json node_modules"
  - "npm install -g gatsby"
script:
  - "yarn install && yarn run deploy"