backend:
  name: github
  repo: GianW/GianW.github.io
  branch: source
  site_domain: clever-mcclintock-6cc558.com

publish_mode: editorial_workflow
media_folder: "content/assets"
public_folder: "assets/"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "seo", name: "seo", widget: "string" }
      - { label: "tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "brain" # Used in routes, e.g., /admin/collections/blog
    label: "Brain" # Used in the UI
    folder: "content/brain" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "SEO", name: "seo", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }